### ISSUE TITLE
Execute script every X minute.

### ISSUE THREAD

**Issue by docccccc** [VR-25/djs#17]
Hi,
Thanks for this awesome module. 
Is it possible to add the ability to execute scripts every certain time?

For example,
I want to execute script every 1 minute. And so, I have to add 1440 lines to config.txt.  A little big :)

**Comment by VR-25** [comment]
Although not as flexible as crontab's syntax, one can do a lot with DJS' seemingly _too basic_ rules.

To run a script every minute, a loop can be used. Remember that a shell script has high flexibility.

`boot while true; do run_script; sleep 60; done`

Of course, instead of `boot`,  a time can be used as starting point instead.

Using both (e.g., for fail safe runs) also works:

`0700 while :; do run_script; sleep 60; done; : --boot`

**Comment by docccccc** [comment]
Great! Its working. :) 
Thanks.
